name: Update DNS IP & DoH List

on:
  schedule:
    - cron: '0 2 * * *'   # Setiap hari jam 09:00 WIB
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update file daftar DNS
        run: |
          echo "# DNS IP Publik Direkomendasikan (Indonesia)" > dns-ip-list.txt
          echo "# Updated: 2025-05-21 02:53:19 UTC" >> dns-ip-list.txt
          echo "" >> dns-ip-list.txt
          echo "1.1.1.1" >> dns-ip-list.txt
          echo "8.8.8.8" >> dns-ip-list.txt
          echo "9.9.9.9" >> dns-ip-list.txt
          echo "208.67.222.222" >> dns-ip-list.txt
          echo "94.140.14.14" >> dns-ip-list.txt
          echo "" >> dns-ip-list.txt

          echo "# DNS-over-HTTPS (DoH) Recommended List - Indonesia" > dns-doh-list.txt
          echo "# Updated: 2025-05-21 02:53:19 UTC" >> dns-doh-list.txt
          echo "" >> dns-doh-list.txt
          echo "https://dns.adguard.com/dns-query" >> dns-doh-list.txt
          echo "https://cloudflare-dns.com/dns-query" >> dns-doh-list.txt
          echo "https://dns.quad9.net/dns-query" >> dns-doh-list.txt
          echo "https://doh.opendns.com/dns-query" >> dns-doh-list.txt
          echo "https://doh.cleanbrowsing.org/doh/family-filter/" >> dns-doh-list.txt

      - name: Commit dan Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dns-ip-list.txt dns-doh-list.txt
          git commit -m "Update otomatis DNS IP & DoH list" || echo "Tidak ada perubahan"
          git push
